const themes = {
  blue: {
    primaryColor: 'bg-blue-500',
    primaryColorDark: 'bg-blue-600',
    secondaryColor: 'bg-cyan-500',
    primaryGradient: 'from-cyan-500 to-blue-500',
    secondaryGradient: 'from-blue-500 to-blue-600',
    primaryButton: 'bg-blue-600 hover:bg-blue-700',
    secondaryButton: 'bg-blue-100 text-blue-700 hover:bg-blue-200',
    textColor: 'text-blue-500',
    background: 'bg-blue-50',
    backgroundDark: 'bg-blue-100',
  },
  red: {
    primaryColor: 'bg-red-500',
    primaryColorDark: 'bg-red-600',
    secondaryColor: 'bg-orange-500',
    primaryGradient: 'from-orange-500 to-red-500',
    secondaryGradient: 'from-red-500 to-red-600',
    primaryButton: 'bg-red-600 hover:bg-red-700',
    secondaryButton: 'bg-red-100 text-red-700 hover:bg-red-200',
    textColor: 'text-red-500',
    background: 'bg-red-50',
    backgroundDark: 'bg-red-100',
  },
  green: {
    primaryColor: 'bg-green-500',
    primaryColorDark: 'bg-green-600',
    secondaryColor: 'bg-cyan-500',
    primaryGradient: 'from-cyan-500 to-green-500',
    secondaryGradient: 'from-sky-500 to-green-600',
    primaryButton: 'bg-green-600 hover:bg-green-700',
    secondaryButton: 'bg-green-100 text-green-700 hover:bg-green-200',
    textColor: 'text-green-500',
    background: 'bg-green-50',
    backgroundDark: 'bg-green-100',
  },
  purple: {
    primaryColor: 'bg-purple-500',
    primaryColorDark: 'bg-purple-600',
    secondaryColor: 'bg-blue-500',
    primaryGradient: 'from-blue-500 to-purple-500',
    secondaryGradient: 'from-sky-500 to-purple-600',
    primaryButton: 'bg-purple-600 hover:bg-purple-700',
    secondaryButton: 'bg-purple-100 text-purple-700 hover:bg-purple-200',
    textColor: 'text-purple-500',
    background: 'bg-purple-50',
    backgroundDark: 'bg-purple-100',
  },
  pink: {
    primaryColor: 'bg-pink-500',
    primaryColorDark: 'bg-pink-600',
    secondaryColor: 'bg-purple-500',
    primaryGradient: 'from-purple-500 to-pink-500',
    secondaryGradient: 'from-purple-500 to-pink-600',
    primaryButton: 'bg-pink-600 hover:bg-pink-700',
    secondaryButton: 'bg-pink-100 text-pink-700 hover:bg-pink-200',
    textColor: 'text-pink-500',
    background: 'bg-pink-50',
    backgroundDark: 'bg-pink-100',
  },
  yellow: {
    primaryColor: 'bg-yellow-400',
    primaryColorDark: 'bg-yellow-500',
    secondaryColor: 'bg-yellow-500',
    primaryGradient: 'from-orange-500 to-yellow-400',
    secondaryGradient: 'from-orange-500 to-yellow-600',
    primaryButton: 'bg-yellow-400 hover:bg-yellow-500',
    secondaryButton: 'bg-yellow-100 text-yellow-700 hover:bg-yellow-200',
    textColor: 'text-yellow-400',
    background: 'bg-yellow-50',
    backgroundDark: 'bg-yellow-100',
  }
}

export { themes }
